# torchrun --nproc-per-node 1 train.py --cfg-path train_configs/minigptv2_finetune.yaml
model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "llama-2-7b-chat-hf"
  ckpt: "/MiniGPT4-v2/checkpoints/checkpoint_stage3.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  grounding_SLAKE:   
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  mimic_cxr:  
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  radvqa:   
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  # rsna:  
  #   batch_size: 6
  #   vis_processor:
  #     train:
  #       name: "blip2_image_train"
  #       image_size: 448
  #   text_processor:
  #     train:
  #       name: "blip_caption"

  # refer_rsna:  
  #   batch_size: 6
  #   vis_processor:
  #     train:
  #       name: "blip2_image_train"
  #       image_size: 448
  #   text_processor:
  #     train:
  #       name: "blip_caption"

  # identify_rsna:  
  #   batch_size: 6
  #   vis_processor:
  #     train:
  #       name: "blip2_image_train"
  #       image_size: 448
  #   text_processor:
  #     train:
  #       name: "blip_caption"

  nlst:   
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
        
  refer_nlst:  
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

  identify_nlst:  
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
      

run:
  task: image_text_pretrain
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 100
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 1000
  
  seed: 42
  output_dir: "expermints_folder"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune_final